### ISSUE TITLE
Question about config.ini

### ISSUE THREAD

**Issue by TR1D** [TortoiseOrHare/NoCheatZ-4#200]
How should the steamid administrators be indicated?
Checked in this form: admin_ids=STEAM_0:0:0000000
But still administrators see anti-cheat messages.

**Comment by L-EARN** [comment]
This feature is here so that only admins see chat messages from nocheatz when you set `ncz Logger AllowChat admin.` If you want to completly remove chat messages, just use `ncz Logger AllowChat off`.

`admin_ids=STEAM_0:0:0000000;STEAM_0:0:0000001;STEAM_0:0:0000002`

It should match exactly how the game represents steamids.
So maybe you have to put : 
`admin_ids=[U:1:0000000];[U:1:0000001];[U:1:0000002]`

**Comment by TR1D** [comment]
Tried admin_ids=[U:1:0000000]
But as with STEAM_0: 0: 0000000 messages are visible to all administrators

**Comment by warlock396** [comment]
Same, i want to make what just i can see messages, but messages can see all admis on server.
Using Sourcebans for making admins, and i write in config.ini just mine steam_id, but anyway messages can see all admins.

**Comment by L-EARN** [comment]
Ah ok now I understand what you mean.

The thing is : when the sm_chat command is found nocheatz will use it instead of admins_ids.

**Comment by TR1D** [comment]
More recently, in previous releases there have been false positives.
I would not want to show it to everyone.
Is it possible, even if the sourcemod is installed, to enable admin_ids =
