### ISSUE TITLE
Another ban issue / People getting stuck in the middle of nowhere

### ISSUE THREAD

**Issue by hooliganxxx** [TortoiseOrHare/NoCheatZ-4#208]
Hi, the description will be vague due to there is no clear evidence but just claims from my players...

My `AllowWriteBans No`

There were 2 of my players today, contacting me and claiming they were banned from the server - however, they were not appearing in the banlist `csgo.cs-derzkiy.ru`, but still stating they could not enter ther server. 
I checked banned_user.cfg and banned_ip.cfg - they were clear as well. 
In NCZ logs - they were deceted positive by MouseTester, (with 1 detections and a really small delta - between 0 and 1) so I assumed they did get banned. 

However, when I restarted the server - they were able to get in. So hence the question. 
Is it possible that for some reason sourcemod didnot proccess the ban, and since allowwritebans was off, these bans somehow stuck in the middle (making people unable to enter, and as wel not writing them down in bans.cfg)? 
We know the native ban system is pretty weird in csgo, so I assume it is possible that this problem somehow causes that weird thing to happen. 

Scheme; 
1. NCZ detects and attempts to ban
2. Sourcemod fails to add ban
3. Allowritebans No, so files aren't changed, however the info about ban is still in cache or something
4. Players can't get in, all banlist files are clear
5. Server restarts, reloading banlists - the cache or something disappears, ban info disappearing as well
6. Those players can get on server now. 

If this keeps happening, and bans happen to be false positive - it will cause problems with
a) constant server restaring to allow those stuck people get in
b) will allow cheater players (real cheaters who get stuck as well) enter the server after those restarts.

Possible asoultion, also kind like a  feature:
Add another cvar that would let us choose the banning methods, for example like

`BanningMethod = [command] [userid] [reason] [length]>`

Where we could enter our own data - since some of us use third-party or self-developed banning, with our own commands (not just sm_ban, but dy_ban, fb_ban, etc)

Thanks.
And again, I would love to donate you some money some time in a while, if you could just reveal a link somewhere to do so - would be nice!

UDP
If you want to replicate the issue, use linux + your 30th release (r62) metamod and sourcemod. AllowWriteBans to No, and try to get banned then unban yourself and then try to get banned again.

**Comment by L-EARN** [comment]
Hi,

Do you have any log showing that sourcebans failed, from sourcemod logs ?

**Comment by hooliganxxx** [comment]
Ok, now here is the thing. 
One of the bans happened on august 1st, at 13:16 (See screenshots).
NCZ logs indicate detection and later banning,
but when I go to sourcemod logs - there is just no information about that happening at all - though it logs everything -- the other bans made by ncz with chat messages and so on.
![1](https://user-images.githubusercontent.com/30504700/28873984-97fa545c-7798-11e7-8a55-a63808a4cf6d.PNG)
![2](https://user-images.githubusercontent.com/30504700/28873983-97fa5db2-7798-11e7-941d-8170f7a36bb9.PNG)

**Comment by hooliganxxx** [comment]
Now I noticed it did not log the ban that happened right after that at 13:22 with bunny hop injected, 
Everything that happened during these 4 minutes on de_dust2. 
And as I was mentioning in previous issues (https://github.com/L-EARN/NoCheatZ-4/issues/206)
I had a lot of those people in user_banned.cfg right before I turned allowwritebans to no.

**Comment by L-EARN** [comment]
You are sending me logs from a previous version of the plugin.
The mousetester changed a lot since then. In fact, it become very more stable. And the name changed from "MouseTester_BETA" to "MouseTester" (Which I forgot to replicate in nocheatz.cfg though).

Please download r65, make sure it is loading the correct version.
Also run your server with condebug as well, if you want.
**If you have logs with r63 or r65 with the same issue, please send them.**

The bug you describe is not really possible with r65 : 
- NoCheatZ sends ban info to SM if sm_ban command is present.
- If userid is not valid for some reason, nocheatz will use sm_addban instead with Steam ID ... if sm_ban was present still.
- After that, nocheatz forces every server commands to process. (So SM processes bans at the moment)
- Then NoCheatZ process a kick on the client to be sure (And also to inform other systems of nocheatz that this client must not be processed anymore. Otherwise they could crash).
- To finish, NoCheatZ is now aware he should write ids and ips. But he will never until he is allowed to.

https://github.com/L-EARN/NoCheatZ-4/blob/master/server-plugin/Code/Systems/BanRequest.cpp#L180

**Comment by hooliganxxx** [comment]
Yeah, I updated to r65 as soon as it came out.

**Comment by L-EARN** [comment]
Ok. I'm waiting for more info. Thank you.

But I might also add that sometimes when I test I get banned, I unban myself but it's not enough : I get some sort of "You have to be in a lobby to join the server". So I restart (While being mad ^^) ...

Moreover, it could also be related to #167

**Comment by hooliganxxx** [comment]
This is exactly what i'm talking about - this lobby thing. People either get normal sourceban or this lobby thing and can't connect. When you are getting in this lobby - you get inside what I tried to explain as in the middle.

**Comment by L-EARN** [comment]
Well. It's the valve way of handling connections.

From what I unserdtand : 
- The client in his game ask to connect.
- The master server of valve creates a timed ticket (So someone who tried to connect after with a lower latency will not steal your slot).
- The client knocks the server.
- The server asks valve's master server if the client can connect.
- Yes ... or no.

What happens when we get banned ? I can't really answer ... I'm not a valve employee (I will never be).

**Comment by hooliganxxx** [comment]
That is why I personally want you to make it fully customizable the way plugin bans.

**Comment by hooliganxxx** [comment]
just to give you some idea of the way to implement it - here is a screenshot of the anticheat at my cs1.6 server.
It contains reason and punishment. You can add per say
`MouseTester Punishment` where punishment includes certain variables.
![default](https://user-images.githubusercontent.com/30504700/28877297-9ccd52ac-77a4-11e7-9ffb-9b1ce08823e8.PNG)

**Comment by L-EARN** [comment]
I'm not sure it will change anything unless your other ways don't use game native bans at 100%.

And now I understand better why sourcemod uses a SQL database to store bans ...

But now. Why sourcemod failed to ban ? If it didn't, why nocheatz failed to detect sm_ban ? Also, can I implement a native system to ban/unban players without using game bans (Yes I can) ?

**Comment by hooliganxxx** [comment]
That is a good question. That is why I will record console to see where it went wrong. 
With any other plugins it never failed to recognize command. Is there somewhere an error that makes for repetitive commands, or send two at a same time or a single line? 
Unfortunately, I'm a poor coder - I only worked with php in my life, so I wouldnt be very useful, but i would love to help where possible.

**Comment by hooliganxxx** [comment]
SQL also wins in time the more bans you have on record.

**Comment by L-EARN** [comment]
_With any other plugins it never failed to recognize commands. Is there somewhere an error that makes for repetitive commands, or send two at a same time or a single line?_

You elevated my head.
What if 2 testers trigger detections in the same stack ?
I need to test that.

**Comment by hooliganxxx** [comment]
Issue seems to be gone. Got 2 days of console regs but didnt see no bans nomore. Sorry for distracting.
