### ISSUE TITLE
[QUESTION-REQUEST] WH | BLOCK WH| BLOCK ESP

### ISSUE THREAD

**Issue by BlackYuzia** [TortoiseOrHare/NoCheatZ-4#213]
Hello @L-EARN ,
I have a question.
Now 

> Block wh

 how work?
I will be enabled him. But I not see anychanges.
Or that func not worked?

I hope you will be added Great Block WH, and cheaters can't see anythink with walls.

**Comment by L-EARN** [comment]
Hi,

Read #199 and #190 ... again.

**Comment by BlackYuzia** [comment]
@L-EARN oy, srry

**Comment by BlackYuzia** [comment]
But I do not find anythink new D:

**Comment by L-EARN** [comment]
There is no change because nothing have changed.

I didn't worked on it and it's not even planned to do at the moment.

The priority is to detect, not to block.

I have a good project that could blow everyone's mind. But I need to make decisions and compromises for that, and you need to be patient for it too.

This is just not a priority for me.
But if it is for you, you're free to fix the code yourself.

**Comment by BlackYuzia** [comment]
@L-EARN If I can I do it :d 
Okey, But HOW you can detect WH? That (maybe) inpossible.
