### ISSUE TITLE
Aimbot styles, improving your testers

### ISSUE THREAD

**Issue by hooliganxxx** [TortoiseOrHare/NoCheatZ-4#215]
Hi, not so long ago I came around a forum, where cheaters and cheat makers discuss the coding behind their cheats, and make up new style cheats, that are hard to detect. 
I want to share the link with you, however, I do not want to make it pulic, so more people would now about this place, go there and get cheats, if you know what I mean. 

Github had removed private messaging feature long ago, so im not sure how to pass a link to you without making it public. The only reason I want to share the link with you as because it will help you produce even stronger testers, and make your anticheat much better and more detective.

Please give me some kind of way to send you the link so you could just wonder around the threads, see if there are things you didnt know about and how to block or detect those. 
. Thanks

**Comment by Weeeishy** [comment]
I'm pretty sure he is aware of these forums, plus they are not hard. I can think of 3 forums atm and they start with U, M, and H. Lol go figure

**Comment by L-EARN** [comment]
Hi,

I'm aware of these sites.

Don't feel so surprised : I also used to be a cheater.

I know how cheats are made (I also used to made my own cheat on CS:S), I know how they will evolve against upcoming anti cheats features and I'm still convinced anti cheats will win at the end because we will force cheat makers to nerf cheat features to stay undetected, meaning at the end a cheat will just replicate what a human can do, so it will become useless to cheat.
