### ISSUE TITLE
[REQUEST-QUESTION] Support with Admin ESP/WH

### ISSUE THREAD

**Issue by BlackYuzia** [TortoiseOrHare/NoCheatZ-4#230]
hello,
I find one bug (with **WALLHACK BLOCK**)
When I install to server the **Adanvsed Admin ESP/WH** or the **Admin ESP**
I get a bug, when **WH BLOCK** not work.
All players are visible in all type blocks (prop/no-prop/wall, etc)

And, I have a request-question.
You can add support this **Adanvsed Admin ESP/WH** and **Admin ESP**?

There's plugins: https://github.com/MitchDizzle/Advanced-Admin-ESP
(I think **Admin ESP** works the same way.)

**Comment by hooliganxxx** [comment]
did you test it from different accounts? 
What I mean whblock is not working for you because esp plugin transmits entities to you since you are admin, and that's how plugin works. But WHblocker might still work for those who are not admins, since no plugin is sending them that information about players behind the wall.

**Comment by BlackYuzia** [comment]
Oh. I think that for all. :s

Okey. I test it
