### ISSUE TITLE
[REQUEST] Anti Aim Detector

### ISSUE THREAD

**Issue by BlackYuzia** [TortoiseOrHare/NoCheatZ-4#235]
Hello,
I see a one guy in to my server who use Anti Aim. (That is func **RAGE HACK**)
He **spin** or look at down/up/left other.

I watch, and I see.
He detect so many times. But He detect to slowly.
I mean, He play 1-5 rounds and he not get BAN.
Only when he killing so many players and play many rounds he get ban.
**That will be bad.** 

When I check logs, I see - he detect in reason: **Auto Attack** 
Can you add own reason: **Anti Aim** (**Rage hack** or etc)
And check Angle. When and how he look in game.
He spin, and other.

I think that will be help for speedly detect him (Rage Cheats)

Thanks.

**Comment by L-EARN** [comment]
It's sad because autoattacktester will be removed as well.

But you have to understand that every testers will check for some specific issues about cheats.
And the majority of the testers are now fixed by cheat providers ...

In short, the majority of NCZ is not working today.

I'm closing this because there is no real issue from my point of view, but I understand what you mean don't worry. I will find a way.
